import {
  Mail,
  Lock,
  Phone,
  User,
  BadgeCheck,
  Eye,
  EyeOff,
  LayoutDashboard,
  CreditCard,
  ClipboardCheck,
  Settings,
  LogOut,
  Menu,
  Bell,
  MessageSquare,
  Building2,
  Users,
  Home,
  Search,
  Heart,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  Briefcase,
  Calendar,
  Hash,
  Globe,
  Facebook,
  Badge,
  Ban,
  CheckCircle,
  ClipboardList,
  Info,
  ShieldCheck,
  X,
  MapPin,
} from "lucide-react";

export const Icons = {
  mail: Mail,
  lock: Lock,
  phone: Phone,
  user: User,
  eye: Eye,
  eyeOff: EyeOff,

  dashboard: LayoutDashboard,
  billing: CreditCard,
  review: ClipboardCheck,

  settings: Settings,
  logout: LogOut,

  menu: Menu,
  bell: Bell,
  messages: MessageSquare,
  messagesSquare: MessageSquare,

  building: Building2,
  users: Users,
  home: Home,
  search: Search,
  heart: Heart,
  layoutDashboard: LayoutDashboard,
  creditCard: CreditCard,
  logOut: LogOut,
  info: Info,
  shieldCheck: ShieldCheck,

  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowLeft: ArrowLeft,
  briefcase: Briefcase,
  calendar: Calendar,
  hash: Hash,
  globe: Globe,
  facebook: Facebook,
  badge: Badge,
  ban: Ban,
  block: Ban,
  checkCircle: CheckCircle,
  clipboardList: ClipboardList,
  close: X,
  mapPin: MapPin,
};

export function Icon({ name, size = 18, className = "" }) {
  const Cmp = Icons[name];
  if (!Cmp) return null;
  return <Cmp size={size} className={className} />;
}
